// Code generated by wit-bindgen-go. DO NOT EDIT.

package console

// This file contains wasmimport and wasmexport declarations for "web:std@0.1.0".

//go:wasmimport web:std/console@0.1.0 log
//go:noescape
func wasmimport_Log(message0 *uint8, message1 uint32)

//go:wasmimport web:std/console@0.1.0 warn
//go:noescape
func wasmimport_Warn(message0 *uint8, message1 uint32)

//go:wasmimport web:std/console@0.1.0 error
//go:noescape
func wasmimport_Error(message0 *uint8, message1 uint32)

//go:wasmimport web:std/console@0.1.0 info
//go:noescape
func wasmimport_Info(message0 *uint8, message1 uint32)

//go:wasmimport web:std/console@0.1.0 debug
//go:noescape
func wasmimport_Debug(message0 *uint8, message1 uint32)

//go:wasmimport web:std/console@0.1.0 assert
//go:noescape
func wasmimport_Assert(assertion0 uint32, message0 *uint8, message1 uint32)

//go:wasmimport web:std/console@0.1.0 time
//go:noescape
func wasmimport_Time(label0 *uint8, label1 uint32)

//go:wasmimport web:std/console@0.1.0 time-end
//go:noescape
func wasmimport_TimeEnd(label0 *uint8, label1 uint32)
