// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package console represents the imported interface "web:std/console@0.3.1".
package console

import (
	"go.bytecodealliance.org/cm"
)

// Log represents the imported function "log".
//
//	log: func(message: string)
//
//go:nosplit
func Log(message string) {
	message0, message1 := cm.LowerString(message)
	wasmimport_Log((*uint8)(message0), (uint32)(message1))
	return
}

// Warn represents the imported function "warn".
//
//	warn: func(message: string)
//
//go:nosplit
func Warn(message string) {
	message0, message1 := cm.LowerString(message)
	wasmimport_Warn((*uint8)(message0), (uint32)(message1))
	return
}

// Error represents the imported function "error".
//
//	error: func(message: string)
//
//go:nosplit
func Error(message string) {
	message0, message1 := cm.LowerString(message)
	wasmimport_Error((*uint8)(message0), (uint32)(message1))
	return
}

// Info represents the imported function "info".
//
//	info: func(message: string)
//
//go:nosplit
func Info(message string) {
	message0, message1 := cm.LowerString(message)
	wasmimport_Info((*uint8)(message0), (uint32)(message1))
	return
}

// Debug represents the imported function "debug".
//
//	debug: func(message: string)
//
//go:nosplit
func Debug(message string) {
	message0, message1 := cm.LowerString(message)
	wasmimport_Debug((*uint8)(message0), (uint32)(message1))
	return
}

// Assert represents the imported function "assert".
//
//	assert: func(assertion: bool, message: string)
//
//go:nosplit
func Assert(assertion bool, message string) {
	assertion0 := (uint32)(cm.BoolToU32(assertion))
	message0, message1 := cm.LowerString(message)
	wasmimport_Assert((uint32)(assertion0), (*uint8)(message0), (uint32)(message1))
	return
}

// Time represents the imported function "time".
//
//	time: func(label: string)
//
//go:nosplit
func Time(label string) {
	label0, label1 := cm.LowerString(label)
	wasmimport_Time((*uint8)(label0), (uint32)(label1))
	return
}

// TimeEnd represents the imported function "time-end".
//
//	time-end: func(label: string)
//
//go:nosplit
func TimeEnd(label string) {
	label0, label1 := cm.LowerString(label)
	wasmimport_TimeEnd((*uint8)(label0), (uint32)(label1))
	return
}
