// Code generated by wit-bindgen-go. DO NOT EDIT.

package fetch

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// FetchErrorShape is used for storage in variant or result types.
type FetchErrorShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(FetchError{})]byte
}

func lower_OptionListU8(v cm.Option[cm.List[uint8]]) (f0 uint32, f1 *uint8, f2 uint32) {
	some := v.Some()
	if some != nil {
		f0 = 1
		v1, v2 := cm.LowerList(*some)
		f1 = (*uint8)(v1)
		f2 = (uint32)(v2)
	}
	return
}

func lower_Request(v Request) (f0 *uint8, f1 uint32, f2 uint32, f3 *Header, f4 uint32, f5 uint32, f6 *uint8, f7 uint32) {
	f0, f1 = cm.LowerString(v.URL)
	f2 = (uint32)(v.Method)
	f3, f4 = cm.LowerList(v.Headers)
	f5, f6, f7 = lower_OptionListU8(v.Body)
	return
}
