// Code generated by wit-bindgen-go. DO NOT EDIT.

package fetch

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "web:std@0.3.1".

//go:wasmimport web:std/fetch@0.3.1 [resource-drop]response
//go:noescape
func wasmimport_ResponseResourceDrop(self0 uint32)

//go:wasmimport web:std/fetch@0.3.1 [method]response.bytes
//go:noescape
func wasmimport_ResponseBytes(self0 uint32, result *cm.List[uint8])

//go:wasmimport web:std/fetch@0.3.1 [method]response.headers
//go:noescape
func wasmimport_ResponseHeaders(self0 uint32, result *cm.List[Header])

//go:wasmimport web:std/fetch@0.3.1 [method]response.ok
//go:noescape
func wasmimport_ResponseOK(self0 uint32) (result0 uint32)

//go:wasmimport web:std/fetch@0.3.1 [method]response.status
//go:noescape
func wasmimport_ResponseStatus(self0 uint32) (result0 uint32)

//go:wasmimport web:std/fetch@0.3.1 [method]response.status-text
//go:noescape
func wasmimport_ResponseStatusText(self0 uint32, result *string)

//go:wasmimport web:std/fetch@0.3.1 [method]response.text
//go:noescape
func wasmimport_ResponseText(self0 uint32, result *string)

//go:wasmimport web:std/fetch@0.3.1 fetch
//go:noescape
func wasmimport_Fetch(request0 *uint8, request1 uint32, request2 uint32, request3 *Header, request4 uint32, request5 uint32, request6 *uint8, request7 uint32) (result0 uint32)
