// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package fetch represents the imported interface "web:std/fetch@0.3.1".
package fetch

import (
	"go.bytecodealliance.org/cm"
)

// Method represents the enum "web:std/fetch@0.3.1#method".
//
//	enum method {
//		get,
//		head,
//		post,
//		put,
//		delete,
//		patch,
//		options
//	}
type Method uint8

const (
	MethodGet Method = iota
	MethodHead
	MethodPost
	MethodPut
	MethodDelete
	MethodPatch
	MethodOptions
)

var _MethodStrings = [7]string{
	"get",
	"head",
	"post",
	"put",
	"delete",
	"patch",
	"options",
}

// String implements [fmt.Stringer], returning the enum case name of e.
func (e Method) String() string {
	return _MethodStrings[e]
}

// MarshalText implements [encoding.TextMarshaler].
func (e Method) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements [encoding.TextUnmarshaler], unmarshaling into an enum
// case. Returns an error if the supplied text is not one of the enum cases.
func (e *Method) UnmarshalText(text []byte) error {
	return _MethodUnmarshalCase(e, text)
}

var _MethodUnmarshalCase = cm.CaseUnmarshaler[Method](_MethodStrings[:])

// Header represents the record "web:std/fetch@0.3.1#header".
//
//	record header {
//		name: string,
//		value: string,
//	}
type Header struct {
	_     cm.HostLayout `json:"-"`
	Name  string        `json:"name"`
	Value string        `json:"value"`
}

// Request represents the record "web:std/fetch@0.3.1#request".
//
//	record request {
//		url: string,
//		method: method,
//		headers: list<header>,
//		body: option<list<u8>>,
//	}
type Request struct {
	_       cm.HostLayout             `json:"-"`
	URL     string                    `json:"url"`
	Method  Method                    `json:"method"`
	Headers cm.List[Header]           `json:"headers"`
	Body    cm.Option[cm.List[uint8]] `json:"body"`
}

// FetchError represents the variant "web:std/fetch@0.3.1#fetch-error".
//
//	variant fetch-error {
//		network-error(string),
//		timeout,
//	}
type FetchError cm.Variant[uint8, string, string]

// FetchErrorNetworkError returns a [FetchError] of case "network-error".
func FetchErrorNetworkError(data string) FetchError {
	return cm.New[FetchError](0, data)
}

// NetworkError returns a non-nil *[string] if [FetchError] represents the variant case "network-error".
func (self *FetchError) NetworkError() *string {
	return cm.Case[string](self, 0)
}

// FetchErrorTimeout returns a [FetchError] of case "timeout".
func FetchErrorTimeout() FetchError {
	var data struct{}
	return cm.New[FetchError](1, data)
}

// Timeout returns true if [FetchError] represents the variant case "timeout".
func (self *FetchError) Timeout() bool {
	return self.Tag() == 1
}

var _FetchErrorStrings = [2]string{
	"network-error",
	"timeout",
}

// String implements [fmt.Stringer], returning the variant case name of v.
func (v FetchError) String() string {
	return _FetchErrorStrings[v.Tag()]
}

// Response represents the imported resource "web:std/fetch@0.3.1#response".
//
//	resource response
type Response cm.Resource

// ResourceDrop represents the imported resource-drop for resource "response".
//
// Drops a resource handle.
//
//go:nosplit
func (self Response) ResourceDrop() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_ResponseResourceDrop((uint32)(self0))
	return
}

// Bytes represents the imported method "bytes".
//
//	bytes: func() -> list<u8>
//
//go:nosplit
func (self Response) Bytes() (result cm.List[uint8]) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_ResponseBytes((uint32)(self0), &result)
	return
}

// Headers represents the imported method "headers".
//
//	headers: func() -> list<header>
//
//go:nosplit
func (self Response) Headers() (result cm.List[Header]) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_ResponseHeaders((uint32)(self0), &result)
	return
}

// OK represents the imported method "ok".
//
//	ok: func() -> bool
//
//go:nosplit
func (self Response) OK() (result bool) {
	self0 := cm.Reinterpret[uint32](self)
	result0 := wasmimport_ResponseOK((uint32)(self0))
	result = (bool)(cm.U32ToBool((uint32)(result0)))
	return
}

// Status represents the imported method "status".
//
//	status: func() -> u16
//
//go:nosplit
func (self Response) Status() (result uint16) {
	self0 := cm.Reinterpret[uint32](self)
	result0 := wasmimport_ResponseStatus((uint32)(self0))
	result = (uint16)((uint32)(result0))
	return
}

// StatusText represents the imported method "status-text".
//
//	status-text: func() -> string
//
//go:nosplit
func (self Response) StatusText() (result string) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_ResponseStatusText((uint32)(self0), &result)
	return
}

// Text represents the imported method "text".
//
//	text: func() -> string
//
//go:nosplit
func (self Response) Text() (result string) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_ResponseText((uint32)(self0), &result)
	return
}

// Fetch represents the imported function "fetch".
//
//	fetch: func(request: request) -> future<result<response, fetch-error>>
//
//go:nosplit
func Fetch(request Request) (result cm.Future[cm.Result[FetchErrorShape, Response, FetchError]]) {
	request0, request1, request2, request3, request4, request5, request6, request7 := lower_Request(request)
	result0 := wasmimport_Fetch((*uint8)(request0), (uint32)(request1), (uint32)(request2), (*Header)(request3), (uint32)(request4), (uint32)(request5), (*uint8)(request6), (uint32)(request7))
	result = cm.Reinterpret[cm.Future[cm.Result[FetchErrorShape, Response, FetchError]]]((uint32)(result0))
	return
}
