// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package types represents the imported interface "web:document/types@0.1.1".
package types

import (
	"go.bytecodealliance.org/cm"
)

// Element represents the imported resource "web:document/types@0.1.1#element".
//
//	resource element
type Element cm.Resource

// ResourceDrop represents the imported resource-drop for resource "element".
//
// Drops a resource handle.
//
//go:nosplit
func (self Element) ResourceDrop() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_ElementResourceDrop((uint32)(self0))
	return
}

// Append represents the imported method "append".
//
//	append: func(child: borrow<element>)
//
//go:nosplit
func (self Element) Append(child Element) {
	self0 := cm.Reinterpret[uint32](self)
	child0 := cm.Reinterpret[uint32](child)
	wasmimport_ElementAppend((uint32)(self0), (uint32)(child0))
	return
}

// AppendText represents the imported method "append-text".
//
//	append-text: func(child: borrow<text>)
//
//go:nosplit
func (self Element) AppendText(child Text) {
	self0 := cm.Reinterpret[uint32](self)
	child0 := cm.Reinterpret[uint32](child)
	wasmimport_ElementAppendText((uint32)(self0), (uint32)(child0))
	return
}

// QuerySelector represents the imported method "query-selector".
//
//	query-selector: func(selector: string) -> option<element>
//
//go:nosplit
func (self Element) QuerySelector(selector string) (result cm.Option[Element]) {
	self0 := cm.Reinterpret[uint32](self)
	selector0, selector1 := cm.LowerString(selector)
	wasmimport_ElementQuerySelector((uint32)(self0), (*uint8)(selector0), (uint32)(selector1), &result)
	return
}

// Text represents the imported resource "web:document/types@0.1.1#text".
//
//	resource text
type Text cm.Resource

// ResourceDrop represents the imported resource-drop for resource "text".
//
// Drops a resource handle.
//
//go:nosplit
func (self Text) ResourceDrop() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_TextResourceDrop((uint32)(self0))
	return
}

// Data represents the imported method "data".
//
//	data: func() -> string
//
//go:nosplit
func (self Text) Data() (result string) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_TextData((uint32)(self0), &result)
	return
}

// SetData represents the imported method "set-data".
//
//	set-data: func(value: string)
//
//go:nosplit
func (self Text) SetData(value string) {
	self0 := cm.Reinterpret[uint32](self)
	value0, value1 := cm.LowerString(value)
	wasmimport_TextSetData((uint32)(self0), (*uint8)(value0), (uint32)(value1))
	return
}
