// Code generated by wit-bindgen-go. DO NOT EDIT.

package types

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "web:document@0.3.1".

//go:wasmimport web:document/types@0.3.1 [resource-drop]element
//go:noescape
func wasmimport_ElementResourceDrop(self0 uint32)

//go:wasmimport web:document/types@0.3.1 [method]element.append
//go:noescape
func wasmimport_ElementAppend(self0 uint32, child0 uint32)

//go:wasmimport web:document/types@0.3.1 [method]element.append-text
//go:noescape
func wasmimport_ElementAppendText(self0 uint32, child0 uint32)

//go:wasmimport web:document/types@0.3.1 [method]element.query-selector
//go:noescape
func wasmimport_ElementQuerySelector(self0 uint32, selector0 *uint8, selector1 uint32, result *cm.Option[Element])

//go:wasmimport web:document/types@0.3.1 [resource-drop]text
//go:noescape
func wasmimport_TextResourceDrop(self0 uint32)

//go:wasmimport web:document/types@0.3.1 [method]text.data
//go:noescape
func wasmimport_TextData(self0 uint32, result *string)

//go:wasmimport web:document/types@0.3.1 [method]text.set-data
//go:noescape
func wasmimport_TextSetData(self0 uint32, value0 *uint8, value1 uint32)
