// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package document represents the imported interface "web:document/document@0.1.1".
package document

import (
	"github.com/a-skua/web-wasm/examples/go/internal/web/document/types"
	"go.bytecodealliance.org/cm"
)

// Element represents the imported type alias "web:document/document@0.1.1#element".
//
// See [types.Element] for more information.
type Element = types.Element

// Text represents the imported type alias "web:document/document@0.1.1#text".
//
// See [types.Text] for more information.
type Text = types.Text

// QuerySelector represents the imported function "query-selector".
//
//	query-selector: func(selector: string) -> option<element>
//
//go:nosplit
func QuerySelector(selector string) (result cm.Option[Element]) {
	selector0, selector1 := cm.LowerString(selector)
	wasmimport_QuerySelector((*uint8)(selector0), (uint32)(selector1), &result)
	return
}

// CreateTextNode represents the imported function "create-text-node".
//
//	create-text-node: func(data: string) -> text
//
//go:nosplit
func CreateTextNode(data string) (result Text) {
	data0, data1 := cm.LowerString(data)
	result0 := wasmimport_CreateTextNode((*uint8)(data0), (uint32)(data1))
	result = cm.Reinterpret[Text]((uint32)(result0))
	return
}
