name: Publish
run-name: Publish ${{ github.ref_name }}

on:
  push:
    tags:
      - "*"

permissions: {}

jobs:
  publish:
    runs-on: ubuntu-slim
    environment: publish
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb # v2.0.3
      - run: deno fmt --check
      - run: deno lint
      - run: deno check **/*.ts
      - run: deno publish

  release:
    needs: publish
    runs-on: ubuntu-slim
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: gh release create ${{ github.ref_name }} --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}
